### ISSUE TITLE
Problem after upgrade to 4.14.1 container

### ISSUE THREAD

**Issue by daledude** [lbr38/repomanager#216]
Unfortunately, I don't remember the exact version I was running. Wonder if there is an sqlite upgrade that didn't happen?

Clicking on Tasks or trying to browse any snapshot returns:
```
500: An error occured.
```

Error log:
```
2024/12/09 13:09:59 [error] 429#429: *36 FastCGI sent in stderr: "PHP message: Here is a database error while trying to save log: SQLite3Exception: Unable to prepare statement: table logs has no column named Details in /var/www/repomanager/models/Log/Log.php:63
Stack trace:
#0 /var/www/repomanager/models/Log/Log.php(63): SQLite3->prepare()
#1 /var/www/repomanager/controllers/Log/Log.php(53): Models\Log\Log->log()
#2 /var/www/repomanager/models/Connection.php(1049): Controllers\Log\Log->log()
#3 /var/www/repomanager/models/Repo/Repo.php(156): Models\Connection->logError()
#4 /var/www/repomanager/controllers/Repo/Repo.php(334): Models\Repo\Repo->getAllById()
#5 /var/www/repomanager/controllers/Layout/Container/vars/browse/actions.vars.inc.php(17): Controllers\Repo\Repo->getAllById()
#6 /var/www/repomanager/controllers/Layout/Container/Render.php(22): include_once('...')
#7 /var/www/repomanager/controllers/Layout/Tab/Browse.php(9): Controllers\Layout\Container\Render::render()
#8 /var/www/repomanager/controllers/Layout/Layout.php(25): Controllers\Layout\Tab\Browse:...; PHP message: Here is a the original error that could not be saved in database: An error occured while executing request in database.: SQLite3Exception: Unable to prepare statement: no such column: repos_snap.Pkg_included in /var/www/repomanager/models/Repo/Repo.php:96
Stack trace:
#0 /var/www/repomanager/models/Repo/Repo.php(96): SQLite3->prepare()
#1 /var/www/repomanager/controllers/Repo/Repo.php(334): Models\Repo\Repo->getAllById()
#2 /var/www/repomanager/controllers/Layout/Container/vars/browse/actions.vars.inc.php(17): Controllers\Repo\Repo->getAllById()
#3 /var/www/repomanager/controllers/Layout/Container/Render.php(22): include_once('...')
#4 /var/www/repomanager/controllers/Layout/Tab/Browse.php(9): Controllers\Layout\Container\Render::render()
#5 /var/www/repomanager/controllers/Layout/Layout.php(25): Controllers\Layout\Tab\Browse::render()
#6 /var/www/repomanager/controllers/Controller.php(48): Controllers\Layout\Layout->render()
```

**Comment by lbr38** [comment]
Yes this might be due to a failed database update. Could you please execute

```
docker logs repomanager
```

And check if there is an error message while database update (right after the Repomanager ASCII logo)

![image](https://github.com/user-attachments/assets/b0b44c9b-664f-43cf-9243-43d016f9a25f)

**Comment by daledude** [comment]
Thank you for quick response.

```
Dec 09 13:40:50 conmon[1062269]:  \_  _ \/ __ \\____ \ /  _ \ /     \\__  \ /     \\__  \  / ___\_/ __ \_  __ \
Dec 09 13:40:50 conmon[1062269]:  |  | \|  ___/|  |_> )  (_) )  Y Y  \/ __ \|   |  \/ __ \/ /_/  >  ___/|  | \/
Dec 09 13:40:50 conmon[1062269]:  |__|   \___  >   __/ \____/|__|_|  (____  /___|  (____  |___  / \___  >__|
Dec 09 13:40:50 conmon[1062269]:             \/|__|                \/     \/     \/     \/_____/      \/
Dec 09 13:40:50 conmon[1062269]:
Dec 09 13:40:50 conmon[1062269]:
Dec 09 13:40:50 conmon[1062269]:  Setting permissions...
Dec 09 13:40:53 conmon[1062269]: .
Dec 09 13:40:54 conmon[1062269]:
Dec 09 13:40:54 conmon[1062269]: Databases check and initialization successful
Dec 09 13:40:54 conmon[1062269]:
Dec 09 13:40:54 conmon[1062269]: Enabling maintenance page.
Dec 09 13:40:54 conmon[1062269]: Updating database.
Dec 09 13:40:54 conmon[1062269]: There was an error while executing update: error while executing update file /var/www/repomanager/update/database/4.14.1.php: table requests has 11 columns but 13 values were supplied
Dec 09 13:40:54 conmon[1062269]: Disabling maintenance page.
Dec 09 13:40:59 conmon[1062269]: [Mon Dec 9 13:40:59] Checking for a new version on github...
Dec 09 13:40:59 conmon[1062269]: [Mon Dec 9 13:40:59] Getting notifications...
Dec 09 13:40:59 conmon[1062269]: [Mon Dec 9 13:40:59] Cleaning files
Dec 09 13:40:59 conmon[1062269]: [Mon Dec 9 13:40:59] Running scheduled tasks...
Dec 09 13:40:59 conmon[1062269]: [Mon Dec 9 13:40:59] Running websocket server...
Dec 09 13:41:00 conmon[1062269]: [Mon Dec 9 13:41:00] Running stats parsing...
Dec 09 13:41:00 conmon[1062269]: [Mon Dec 9 13:41:00] Running stats processing...
Dec 09 13:41:10 conmon[1062269]: [Mon Dec 9 13:41:10] Running scheduled tasks...
Dec 09 13:42:10 conmon[1062269]: [Mon Dec 9 13:42:10] Running scheduled tasks...
Dec 09 13:43:10 conmon[1062269]: [Mon Dec 9 13:43:10] Running scheduled tasks...

```

**Comment by lbr38** [comment]
Thanks

This is weird because it looks like you are missing some columns addition from an older version.

Can you please do the following:

1. Enter the container

```
docker exec -it repomanager /bin/bash
```

2. Enter the database

```
cd /var/lib/repomanager/db
sqlite3 repomanager.db
```

3. Print the repos_snap table columns and post the results here please (you can hide the first row of results, I'm only interested in the column names)

```
select * from repos_snap LIMIT 1;
```

4. Exit the actual database
```
.quit
```

5. Enter the hosts database

```
cd /var/lib/repomanager/db
sqlite3 repomanager-hosts.db
```

6. Print the requests table columns and post the restults here please (you can hide the first row of results, I'm only interested in the column names)

```
select * from requests LIMIT 1;
```

7. Exit

```
.quit
```

I will then help you to generate the missing columns if any.

**Comment by daledude** [comment]
Thanks again.

```
root@repomanager:/var/lib/repomanager# cd /var/lib/repomanager/db
root@repomanager:/var/lib/repomanager/db# sqlite3 repomanager.db
-- Loading resources from /root/.sqliterc
SQLite version 3.40.1 2022-12-28 14:03:47
Enter ".help" for usage hints.
sqlite> select * from repos_snap LIMIT 1;
Id  Date        Time   Signed  Arch   Pkg_translation  Type   Reconstruct  Status  Id_repo
--  ----------  -----  ------  -----  ---------------  -----  -----------  ------  -------
1   2024-08-29  18:46  true    amd64                   local               active  1
sqlite>

root@repomanager:/var/lib/repomanager/db# sqlite3 repomanager-hosts.db
-- Loading resources from /root/.sqliterc
SQLite version 3.40.1 2022-12-28 14:03:47
Enter ".help" for usage hints.
sqlite> select * from requests LIMIT 1;
sqlite>
```

**Comment by daledude** [comment]
For completeness:
```
root@repomanager:/var/lib/repomanager/db# sqlite3 repomanager.db
-- Loading resources from /root/.sqliterc
SQLite version 3.40.1 2022-12-28 14:03:47
Enter ".help" for usage hints.
sqlite> PRAGMA table_info(repos_snap);
cid  name             type          notnull  dflt_value  pk
---  ---------------  ------------  -------  ----------  --
0    Id               INTEGER       1                    1
1    Date             DATE          1                    0
2    Time             TIME          1                    0
3    Signed           CHAR(5)       1                    0
4    Arch             VARCHAR(255)  0                    0
5    Pkg_translation  VARCHAR(255)  0                    0
6    Type             CHAR(6)       1                    0
7    Reconstruct      CHAR(8)       0                    0
8    Status           CHAR(8)       1                    0
9    Id_repo          INTEGER       1                    0
sqlite>

root@repomanager:/var/lib/repomanager/db# sqlite3 repomanager-hosts.db
-- Loading resources from /root/.sqliterc
SQLite version 3.40.1 2022-12-28 14:03:47
Enter ".help" for usage hints.
sqlite> PRAGMA table_info(requests);
cid  name           type          notnull  dflt_value  pk
---  -------------  ------------  -------  ----------  --
0    Id             INTEGER       1                    1
1    Date           DATE          1                    0
2    Time           TIME          1                    0
3    Request        VARCHAR(255)  1                    0
4    Status         VARCHAR(255)  1                    0
5    Info           VARCHAR(255)  0                    0
6    Response       VARCHAR(255)  0                    0
7    Response_json  VARCHAR(255)  0                    0
8    Retry          INTEGER       1                    0
9    Next_retry     VARCHAR(255)  0                    0
10   Id_host        INTEGER       1                    0
sqlite>
```

**Comment by lbr38** [comment]
Thanks,

Now please execute the following steps: 

1. Enter the main database

```
cd /var/lib/repomanager/db
sqlite3 repomanager.db
```

2. Add the columns to the repos_snap table:

``` 
ALTER TABLE repos_snap ADD COLUMN Pkg_included VARCHAR(255);
ALTER TABLE repos_snap ADD COLUMN Pkg_excluded VARCHAR(255);
```

3. Also add the following column to the logs table:

```
ALTER TABLE logs ADD COLUMN Details TEXT;
```

4. Exit

```
.quit
```

5. Enter the hosts database

```
cd /var/lib/repomanager/db
sqlite3 repomanager-hosts.db
```

6. Delete the following columns if they still exists:

```
ALTER TABLE ws_requests DROP COLUMN Request_json;
ALTER TABLE ws_requests DROP COLUMN Info_json;
```

7. Exit

```
.quit
```

8. Now just restart the container and see if there are still errors 
```
docker restart repomanager && docker logs repomanager -f
```

**Comment by daledude** [comment]
Thank you so much! Things appear to be ok. Have a great day.

**Comment by lbr38** [comment]
Great!

Please check every tabs and pages and let me know if you see anything wrong or missing. This was a weird bug.

In the future what I would recommend is not to wait too long before updating to the latest image to avoid big jumps in versions.

Also if not already done, do regular backup of the **repomanager-data** volume which should be located in `/var/lib/docker/volumes/repomanager-data` on the host (if you haven't changed the default location). This way you can easily restore the database in case of a bad update.

I will make some documentation on how to do such restore, just in case :)
